### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by TadyTheFish** [duanhong169/ColorPicker#1]
I'm a total beginner in AS. I'm trying to use your library for my app and can't get it working.

colorPickerView.subscribe((color, fromUser) -> {
            // use the color
        });
colorPickerView is colored red (cannot resolve symbol) what did I forgot?

Thank you!

**Comment by duanhong169** [comment]
The `colorPickerView` must be declared and assigned before use.

If you use the `butterknife` library, just do this:

https://github.com/duanhong169/ColorPicker/blob/a2cd044f28b596b8780b11044f1e89d152f55741/app/src/main/java/top/defaults/colorpickerapp/MainActivity.java#L22

or, you can use the `findViewById`:

```java
ColorPickerView colorPickerView = findViewById(R.id. colorPickerView);
```

**Comment by TadyTheFish** [comment]
Thank you so much!
It kinda worked but then the app would crash! The XML file was the problem. I had to change from <top.defaults.view.ColorPickerView to <top.defaults.colorpicker.ColorPickerView because <top.defaults.view.ColorPickerView wuld always return null and it didn't have any preview in the design. It works now!
Thank you!
