### ISSUE TITLE
.show() method should be callable without viewparent

### ISSUE THREAD

**Issue by D4rkness** [duanhong169/ColorPicker#2]
I tried this color picker with i a project and came along an issue, regarding the show method.
So the goal is just to pick a color and store it in an variable, but to do this a view is mandatory, what in this case is not needed.

So could you maybe add the possibility to set the view null, so that no parent is needed ?

**Comment by duanhong169** [comment]
Nice suggestion and I found that the `view` is just unnecessary, will provide a `show()` method without view parent in the next release.
