### ISSUE TITLE
ColorPickerView onMeasure does not account for constrained by height

### ISSUE THREAD

**Issue by faridzidan** [duanhong169/ColorPicker#4]
If I try to constrain the color picker view with height instead of width, it does not show up on the screen at all.

`        android:layout_width="wrap_content" 
        android:layout_height="0dp"

`

![device-2018-09-06-162331](https://user-images.githubusercontent.com/11477995/45183266-9d5aac00-b1f1-11e8-86f1-016d2273054a.png)
![device-2018-09-06-162404](https://user-images.githubusercontent.com/11477995/45183278-a51a5080-b1f1-11e8-88cb-1fb12fcfdfb2.png)

**Comment by duanhong169** [comment]
Sorry, I do not quite understand the issue, what the expected layout?

**Comment by faridzidan** [comment]
ColorPickerView .onMeasure override does not account for ColorPickerView being constrained by height rather than by width. In my use-case I am constraining the ColorPickerView by height and have it wrap_content for width, being placed in a constraint layout with other views above and below it.

`android:layout_width="wrap_content"
android:layout_height="0dp"`

In which case onMeasure fails to compute the desired width and height correctly and the ColorPickerView does not appear on the screen at all.

**Comment by duanhong169** [comment]
Hi, I added a layout for landscape to the sample app using:
        
    android:layout_width="wrap_content"
    android:layout_height="0dp"

And the measure seems work properly:

![image](https://user-images.githubusercontent.com/863999/45819648-79ca5200-bd17-11e8-8c5d-504184358e12.png)

**Comment by faridzidan** [comment]
You don't have anything on top or below the ColorPickerView. What happens if you place a view with height of 96dp to the top of the color view and another view 120dp of height below the ColorPickerView?
I fail to see how this will work considering there is no code in ColorPickerView.onMeasure to handle being constrained by height.

**Comment by duanhong169** [comment]
I tested the layout with top and bottom views:

![image](https://user-images.githubusercontent.com/863999/45854500-06a7f680-bd7e-11e8-9846-d3d56f6eeb4b.png)

**Comment by duanhong169** [comment]
Tested to layout with top and bottom views and didn't see the issue:

![image](https://user-images.githubusercontent.com/863999/45854912-19232f80-bd80-11e8-9110-32f0c74d0b47.png)

**Comment by faridzidan** [comment]
Looks fine in the designer. Using it in an alert dialog with custom view is not working for me as the alert dialog by default uses wrap content for height (causing the color picker not to show up at all), but that's apparently a different issue.
