### ISSUE TITLE
[Request] add option to show/hide brightnessSliderView from ColorPicker

### ISSUE THREAD

**Issue by LossyDragon** [duanhong169/ColorPicker#5]
Hello, 

I'm currently using this color picker as it works with API 28, I like it so far!

However, in my situation, I'm color picker view to to get rgb colors only for communication. The brightness slider currently a waste of space for my current project. 

Example I would like to see within layout: app:enableBrightness="Boolean" or programmatically:  .enableBrightness(Boolean)

Thanks!

**Comment by duanhong169** [comment]
From version 1.1.4, the `app:enableBrightness="Boolean"` or programmatically: `.enableBrightness(Boolean)` is supported.
