### ISSUE TITLE
Cursor release trigger

### ISSUE THREAD

**Issue by ViorelOnica** [duanhong169/ColorPicker#8]
Hello !

Is there any method that will trigger the cursor release after selecting the color?

I tried using this,  but onTouch never gets triggered

![image](https://user-images.githubusercontent.com/27728770/48160575-e3f78000-e2e0-11e8-8c9a-32b7cfef1b7c.png)

**Comment by duanhong169** [comment]
Sorry, what do you mean about "cursor release"?

**Comment by ViorelOnica** [comment]
When you're dragging the finger over the color palette (rgb circle), onColor override gives logs until you lift up your finger off the palette.
I want to receive only one log with the last selected color when you lift up your finger. :)

This is usually checked using setOnTouchListener, when motionEvent is ACTION_UP, but it doesn't work.
